### ISSUE TITLE
ENOENT running the postinstall script

### ISSUE THREAD

**Issue by eugenmihailescu** [gniziemazity/ml-course#1]
Running the `npm install` on any `node` directory of the P3-P9 lessons will throw the following error right after generating the dataset successfully:

```
Error: ENOENT: no such file or directory, open '../common/js_objects/samples.js'
```

The `dataset_generator.js:61` expects the `common/js_objects` directory to exist. While it exists for the P2 lesson, it doesn't for the other lessons.

The solution would be to create the `common/js_objects`directory (if not exists) before running the `npm install`.

**Comment by gniziemazity** [comment]
Thanks for pointing this out (and solving it).
