### ISSUE TITLE
viewer.html crashes the web browser

### ISSUE THREAD

**Issue by eugenmihailescu** [gniziemazity/ml-course#2]
While loading the viewer.html file the web browser crashes (the error message may vary with different browsers). The root cause can be either the web browser V8 engine instance has not enough allocated memory or there are too many open files (.png images).

While the memory error can be mitigated by starting the browser with `--disable-extensions --max_old_space_size=8192` the `too many open files` error may be challenging ([see Linux](https://linuxhint.com/linux_ulimit_command/) `ulimit`).

A better and easier approach would be to use the [image's loading](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/loading) attribute with the value of `lazy`, ie:
```
<img src="..." loading="lazy"/>
```

To fix this change the `createRow` function of `web/js/display.js` file as following:

**BEFORE**
```
...
const img=document.createElement('img');
...
```

**AFTER**
```
...
const img=document.createElement('img');
img.setAttribute("loading","lazy");
...
```

**Comment by gniziemazity** [comment]
Thanks for pointing this out (and solving it).
